language: node_js
node_js:
- '6'
dist: trusty
sudo: required
cache:
  apt: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_3616788c42fc_key -iv $encrypted_3616788c42fc_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "ssarcandy"
- git config --global user.email ssarcandy@gmail.com
- npm install webpack -g
- npm install
script:
- npm run lint
- mkdir dist && cp index.html dist/
- webpack src
- git clone https://github.com/SSARCandy/colorblocks-react gh-pages
- cd gh-pages
- git checkout gh-pages
- cp ../dist/* .
- git remote set-url origin git@github.com:SSARCandy/colorblocks-react.git
- git add . && git commit -m 'update'
- git push
branches:
  only:
  - master
